stages:
  - build
  - test
# Unbedingt eine Leerzeile lassen nach einem Command
image: maven:3.9.6-amazoncorretto-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: build
  tags:
    - docker
  script:
    - mvn compile
  artifacts:
    paths:
      - "target/*"
    expire_in: 2 days
  cache:
    paths:
      - ".m2/repository"

test:
  stage: test
  tags:
    - docker
  dependencies:
    - build
  script:
    - mvn compile
  artifacts:
    paths:
      - "target/*"
    expire_in: 2 days
  cache:
    paths:
      - ".m2/repository"