stages:
  - build
  - test
  - package
  - deploy
# Unbedingt eine Leerzeile lassen nach einem Command
image: maven:3.9.6-amazoncorretto-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

build:
  stage: build
  tags:
    - docker
  script:
    - mvn compile
  artifacts:
    paths:
      - "target/*"
    expire_in: 2 days
  cache:
    paths:
      - ".m2/repository"

test:
  stage: test
  tags:
    - docker
  dependencies:
    - build
  script:
    - mvn compile
  artifacts:
    paths:
      - "target/*"
    expire_in: 2 days
  cache:
    paths:
      - ".m2/repository"

package:
    stage: package
    tags:
        - docker
    dependencies:
        - build
    script:
        - mvn package
    artifacts:
        paths:
        - "target/*.war"
        expire_in: 2 days
    cache:
        paths:
        - ".m2/repository"

deploy_test:
    stage: deploy
    tags:
        - shell
    dependencies:
        - package
    when: manual
    script:
        - docker rm --force tomcat
        - docker image rm --force connect-four
        - docker build -t connect-four .
        - docker run --rm -d --name tomcat -p 8080:8080 connect-four

deploy_test_stop:
  stage: deploy
  tags:
    - shell
  dependencies:
    - package
  when: manual
  script:
    - docker rm --force tomcat
    - docker image rm --force connect-four
  only:
    - test