on: [push]
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - run: mvn compile
      - uses: actions/upload-artifact@v4
        with:
          name: Build-Output
          path: target
          retention-days: 1

  test:
    needs: build
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Build-Output
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - run: mvn test

  package:
    needs: test
    name: Package
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Build-Output
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - run: mvn package
      - uses: actions/upload-artifact@v4
        with:
          name: Package-Output
          path: target/*.war
          retention-days: 2

  deploy_test:
    needs: package
    name: Deploy-Test
    runs-on: self-hosted
    environment:
      name: test
      url: http://localhost:8080/ConnectFour
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Package-Output
      - run: cp ConnectFour.war /usr/local/tomcat/webapps
